/**
 * Render a {@link KnowledgeGraph} to the `architecture.md` skeleton: a component inventory, a
 * dependency summary, and a mermaid diagram. The output is deliberately a *skeleton* — it
 * reports what was observed and leaves interpretation to `findings/`.
 */

import type { Investigation } from "@blacklight/core";
import type { KnowledgeGraph } from "./graph.ts";
import type { GraphEdge, GraphNode } from "./schema.ts";

/** Mermaid node ids must be alphanumeric-ish; map arbitrary ids to safe handles. */
function mermaidId(id: string, seen: Map<string, string>): string {
  const existing = seen.get(id);
  if (existing) return existing;
  const safe = "n" + seen.size + "_" + id.replace(/[^a-zA-Z0-9]/g, "_").slice(0, 24);
  seen.set(id, safe);
  return safe;
}

/** Component-to-component edges that express a dependency. */
function dependencyEdges(edges: GraphEdge[]): GraphEdge[] {
  return edges.filter((e) => e.type === "depends-on" || e.type === "imports");
}

function componentDiagram(nodes: GraphNode[], edges: GraphEdge[]): string {
  if (nodes.length === 0) return "_No components identified._";
  const seen = new Map<string, string>();
  const lines: string[] = ["```mermaid", "graph LR"];
  for (const node of nodes) {
    lines.push(`  ${mermaidId(node.id, seen)}["${node.label}"]`);
  }
  for (const edge of dependencyEdges(edges)) {
    if (!seen.has(edge.from) || !seen.has(edge.to)) continue;
    lines.push(`  ${mermaidId(edge.from, seen)} --> ${mermaidId(edge.to, seen)}`);
  }
  lines.push("```");
  return lines.join("\n");
}

function componentInventory(components: GraphNode[]): string {
  if (components.length === 0) return "_No components identified._";
  const rows = components
    .slice()
    .sort((a, b) => a.label.localeCompare(b.label))
    .map((c) => {
      const fileCount = Array.isArray(c.attrs?.["files"])
        ? (c.attrs["files"] as unknown[]).length
        : (c.attrs?.["fileCount"] ?? "?");
      const path = c.attrs?.["path"] ?? "";
      return `| \`${c.label}\` | ${fileCount} | \`${path}\` |`;
    });
  return ["| Component | Files | Path |", "| --- | --- | --- |", ...rows].join("\n");
}

function dependencySummary(components: GraphNode[], edges: GraphEdge[]): string {
  const byId = new Map(components.map((c) => [c.id, c.label]));
  const deps = dependencyEdges(edges).filter((e) => byId.has(e.from) && byId.has(e.to));
  if (deps.length === 0) return "_No inter-component dependencies identified._";
  return deps
    .slice()
    .sort((a, b) => (byId.get(a.from)! + a.to).localeCompare(byId.get(b.from)! + b.to))
    .map((e) => `- \`${byId.get(e.from)}\` → \`${byId.get(e.to)}\``)
    .join("\n");
}

/** Produce the full `architecture.md` document for an investigation. */
export function renderArchitectureMarkdown(
  graph: KnowledgeGraph,
  investigation: Investigation,
): string {
  const { target, createdAt, blacklightVersion } = investigation;
  const components = graph.nodesOfType("component");
  const { observations, inferences } = graph.provenanceTally();

  return `# Architecture — ${target.name}

> Generated by Blacklight ${blacklightVersion} on ${createdAt}.
> Target: \`${target.rootPath}\` (${target.kind}).
>
> This is an **observation skeleton**: ${observations} observed facts, ${inferences} inferred.
> Interpretation and conclusions belong in \`findings/architecture/\`, not here.

## Components

${componentInventory(components)}

## Dependencies

${dependencySummary(components, graph.allEdges())}

## Component diagram

${componentDiagram(components, graph.allEdges())}

## Graph size

- Nodes: ${graph.nodeCount} (${graph.nodesOfType("file").length} files, ${components.length} components, ${graph.nodesOfType("concept").length} concepts)
- Edges: ${graph.edgeCount}
`;
}
