/** Renderers for the static-analysis-owned artifacts (`unknowns.md`). */

import type { Investigation, Unknown } from "@blacklight/core";

/** Render `unknowns.md` — the honest record of what we could not determine. */
export function renderUnknownsMarkdown(unknowns: Unknown[], investigation: Investigation): string {
  const header = `# Unknowns — ${investigation.target.name}

> Generated by Blacklight ${investigation.blacklightVersion} on ${investigation.createdAt}.
>
> These are things Blacklight could **not** determine. They are recorded, never guessed. See
> RESEARCH-POLICY.md.
`;

  if (unknowns.length === 0) {
    return header + "\n_No unknowns recorded for this pass._\n";
  }

  const items = unknowns
    .map((u) => `- ${u.question}${u.context ? `\n  - _${u.context}_` : ""}`)
    .join("\n");

  return `${header}\n${items}\n`;
}
